import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const control=JSON.parse(fs.readFileSync('governance/v45/control.json','utf8'));
const run=JSON.parse(fs.readFileSync('runs/V45-Z4-WIP-001/run.json','utf8'));
const host=JSON.parse(fs.readFileSync('runs/V45-Z4-WIP-001/evidence/001-host-channel-qualification.json','utf8'));
const jea=JSON.parse(fs.readFileSync('runs/V45-Z4-WIP-001/evidence/002-jea-package-validation.json','utf8'));
const access=JSON.parse(fs.readFileSync('runs/V45-Z4-WIP-001/evidence/003-hostguard-provider-readback-blocker.json','utf8'));
const reconcile=JSON.parse(fs.readFileSync('runs/V45-Z4-WIP-001/evidence/004-hostguard-access-reconcile-package.json','utf8'));
const preflight=JSON.parse(fs.readFileSync('runs/V45-Z4-WIP-001/evidence/005-hostguard-access-preflight-failure.json','utf8'));
const fix=JSON.parse(fs.readFileSync('runs/V45-Z4-WIP-001/evidence/006-hostguard-access-preflight-fix-validation.json','utf8'));
const executionPolicy=JSON.parse(fs.readFileSync('runs/V45-Z4-WIP-001/evidence/007-hostguard-execution-policy-blocker-and-repair-package.json','utf8'));
const executionPolicyPrestate=JSON.parse(fs.readFileSync('runs/V45-Z4-WIP-001/evidence/008-hostguard-execution-policy-prestate-fix.json','utf8'));
const hypervDependency=JSON.parse(fs.readFileSync('runs/V45-Z4-WIP-001/evidence/009-hostguard-hyperv-dependency-blocker-and-repair-package.json','utf8'));
const runtimeDependencies=JSON.parse(fs.readFileSync('runs/V45-Z4-WIP-001/evidence/010-hostguard-runtime-dependencies-blocker-and-repair-package.json','utf8'));
const providerAcceptance=JSON.parse(fs.readFileSync('runs/V45-Z4-WIP-001/evidence/011-hostguard-provider-functional-acceptance.json','utf8'));
const workerBoundary=JSON.parse(fs.readFileSync('runs/V45-Z4-WIP-001/evidence/012-worker-channel-runner-key-boundary.json','utf8'));

test('Z4 records the real privilege boundary instead of pretending VM absence',()=>{
  assert.equal(host.runner_executor,'NT AUTHORITY\\NETWORK SERVICE');
  assert.equal(host.runner_hyperv_read,'DENIED_EXPECTED_PRIVILEGE_BOUNDARY');
  assert.equal(host.guest_ssh22_reachable,true);
  assert.equal(host.existing_fixed_hostguard_service,false);
  assert.equal(host.conclusion,'HOSTGUARD_REQUIRED_DO_NOT_ELEVATE_RUNNER');
});

test('HostGuard prerequisites and runtime dependencies remain repaired with provider functional acceptance PASS',()=>{
  assert.equal(jea.powershell_package_result,'PASS_V45_HOSTGUARD_POWERSHELL51_PACKAGE');
  assert.equal(jea.static_tests_fail,0);
  assert.equal(control.control_version,14);
  assert.equal(control.z4_hostguard_install_required,false);
  assert.equal(control.z4_hostguard_human_install_result,'HOSTGUARD_JEA_INSTALLED');
  assert.equal(control.z4_hostguard_access_reconcile_required,false);
  assert.equal(control.z4_hostguard_access_reconcile_human_result,'HOSTGUARD_JEA_ACCESS_RECONCILED');
  assert.equal(control.z4_hostguard_caller_access_result,'PASS_WITH_ENABLE_NETWORK_ACCESS');
  assert.equal(control.z4_hostguard_execution_policy_reconcile_required,false);
  assert.equal(control.z4_hostguard_execution_policy_human_result,'HOSTGUARD_JEA_EXECUTION_POLICY_RECONCILED');
  assert.equal(control.z4_hostguard_execution_policy_after,'Bypass');
  assert.equal(control.z4_hostguard_hyperv_dependency_reconcile_required,false);
  assert.equal(control.z4_hostguard_hyperv_dependency_human_result,'HOSTGUARD_HYPERV_DEPENDENCY_RECONCILED');
  assert.equal(control.z4_hostguard_runtime_dependencies_reconcile_required,false);
  assert.equal(control.z4_hostguard_runtime_dependencies_human_result,'HOSTGUARD_RUNTIME_DEPENDENCIES_RECONCILED');
  assert.equal(control.z4_hostguard_runtime_dependencies_reconcile_source_commit,'281fbda10677f14ccdfbe0fc43ffcffbfa2385dd');
  assert.equal(control.z4_hostguard_provider_readback,'PASS');
  assert.equal(control.z4_hostguard_shape_diagnostic_run_id,34739129882);
  assert.equal(control.z4_hostguard_shape_diagnostic_job_id,103675695507);
  assert.equal(control.z4_hostguard_host_field_classification,'HOST_FIELD_NULL_REMOTING_BOOT_IDENTITY_PINNED');
  assert.equal(control.z4_hostguard_provider_acceptance_run_id,34739183996);
  assert.equal(control.z4_hostguard_provider_acceptance_job_id,103675841267);
  assert.equal(control.z4_hostguard_provider_acceptance,'PASS');
  assert.equal(control.z4_hostguard_provider_acceptance_evidence,'evidence/011-hostguard-provider-functional-acceptance.json');
  assert.ok(run.evidence_refs.includes('evidence/011-hostguard-provider-functional-acceptance.json'));

  assert.equal(access.classification,'INSTALL_CONFIRMED_FUNCTIONAL_ACCEPTANCE_BLOCKED');
  assert.equal(reconcile.provider_smoke_conclusion,'success');
  assert.equal(preflight.side_effect_classification,'SIDE_EFFECT_NOT_APPLIED');
  assert.equal(fix.provider_smoke_conclusion,'success');
  assert.equal(executionPolicy.root_cause,'PSSC_DEFAULT_EXECUTION_POLICY_RESTRICTED');
  assert.equal(executionPolicyPrestate.side_effect_classification,'SIDE_EFFECT_NOT_APPLIED');
  assert.equal(executionPolicyPrestate.runtime_semantics_observed_omitted_key_effective,'Restricted');
  assert.equal(hypervDependency.root_cause,'HOSTGUARD_MANIFEST_MISSING_HYPERV_REQUIRED_MODULE');
  assert.equal(hypervDependency.package_smoke_conclusion,'success');
  assert.equal(runtimeDependencies.human_hyperv_dependency_reconcile_result,'HOSTGUARD_HYPERV_DEPENDENCY_RECONCILED');
  assert.equal(runtimeDependencies.provider_functional_acceptance_result,'JEA_SESSION_HOSTGUARD_HYPERV_PASSED_CIMCMDLETS_UNRESOLVED');
  assert.equal(runtimeDependencies.root_cause,'HOSTGUARD_MANIFEST_MISSING_CIMCMDLETS_AND_NETTCPIP_REQUIRED_MODULES');
  assert.equal(runtimeDependencies.package_smoke_conclusion,'success');
  assert.deepEqual(runtimeDependencies.required_modules,['Hyper-V','CimCmdlets','NetTCPIP']);
  assert.equal(runtimeDependencies.hyperv_module_loaded,true);
  assert.equal(runtimeDependencies.cimcmdlets_module_loaded,true);
  assert.equal(runtimeDependencies.nettcpip_module_loaded,true);
  assert.equal(runtimeDependencies.get_vm_resolved,true);
  assert.equal(runtimeDependencies.get_cim_instance_resolved,true);
  assert.equal(runtimeDependencies.test_net_connection_resolved,true);
  assert.equal(runtimeDependencies.jea_direct_dependency_cmdlets_exposed_to_caller,false);

  assert.equal(providerAcceptance.human_runtime_dependencies_reconcile_result,'HOSTGUARD_RUNTIME_DEPENDENCIES_RECONCILED');
  assert.deepEqual(providerAcceptance.required_modules,['Hyper-V','CimCmdlets','NetTCPIP']);
  assert.equal(providerAcceptance.shape_diagnostic_conclusion,'success');
  assert.equal(providerAcceptance.shape_object_count,1);
  assert.equal(providerAcceptance.host_field_classification,'HOST_FIELD_NULL_REMOTING_BOOT_IDENTITY_PINNED');
  assert.equal(providerAcceptance.provider_acceptance_conclusion,'success');
  assert.equal(providerAcceptance.provider_acceptance_marker,'PASS_V45_HOSTGUARD_PROVIDER_FUNCTIONAL_ACCEPTANCE');
  assert.equal(providerAcceptance.status_schema,'v45.hostguard.status.v1');
  assert.match(providerAcceptance.boot_identity,/^DESKTOP-1B6PD2P\|/);
  assert.equal(providerAcceptance.vm_name,'PTYSD-WORKER-01');
  assert.equal(providerAcceptance.vm_id,'881f7819-baa9-4a4e-8cca-8f6f18fb89a9');
  assert.equal(providerAcceptance.vm_state,'Running');
  assert.equal(providerAcceptance.guest_ip,'172.31.253.10');
  assert.equal(providerAcceptance.ssh22_reachable,true);
  assert.equal(providerAcceptance.run_as_class,'WINRM_VIRTUAL_ACCOUNT');
  assert.equal(providerAcceptance.ps_computer_name,'localhost');
  assert.equal(providerAcceptance.server_side_exact_host_assertion,'PRESENT_IN_HOSTGUARD_MODULE');
  assert.equal(providerAcceptance.hostguard_provider_functional_acceptance,'PASS');
  assert.equal(providerAcceptance.verification_state,'VERIFIED');
  assert.equal(providerAcceptance.readback_status,'CONFIRMED');
});

test('Z4 advances to the next independent worker-channel gate without regressing HostGuard acceptance',()=>{
  assert.equal(control.z4_hostguard_provider_acceptance,'PASS');
  assert.equal(control.z4_worker_channel_runner_probe_run_id,34739679595);
  assert.equal(control.z4_worker_channel_runner_probe_job_id,103677142640);
  assert.equal(control.z4_worker_channel_runner_probe_result,'BLOCKED_RUNNER_KEY_ACL');
  assert.equal(control.z4_worker_channel_runner_probe_blocker,'NETWORK_SERVICE_ACCESS_DENIED_TO_HUMAN_BREAKGLASS_SSH_KEY');
  assert.equal(control.z4_worker_channel_guest_command_dispatched,false);
  assert.equal(control.z4_worker_channel_admin_readonly_probe_required,true);
  assert.equal(control.z4_worker_channel_admin_readonly_probe_script,'scripts/probe-v45-worker-channel-admin-readonly.ps1');
  assert.equal(control.z4_worker_channel_boundary_evidence,'evidence/012-worker-channel-runner-key-boundary.json');
  assert.equal(control.state,'WAITING_RESOURCE');
  assert.equal(control.wait_reason,'WORKER_CHANNEL_ADMIN_READONLY_PRESTATE_REQUIRED');
  assert.equal(run.state,'WAITING_RESOURCE');
  assert.equal(run.wait_reason,'WORKER_CHANNEL_ADMIN_READONLY_PRESTATE_REQUIRED');
  assert.equal(run.revision,12);
  assert.ok(run.evidence_refs.includes('evidence/012-worker-channel-runner-key-boundary.json'));

  assert.equal(workerBoundary.runner_executor,'NT AUTHORITY\\NETWORK SERVICE');
  assert.equal(workerBoundary.runner_probe_conclusion,'failure');
  assert.equal(workerBoundary.runner_probe_result,'BLOCKED_RUNNER_KEY_ACL');
  assert.equal(workerBoundary.blocker,'NETWORK_SERVICE_ACCESS_DENIED_TO_HUMAN_BREAKGLASS_SSH_KEY');
  assert.equal(workerBoundary.guest_command_dispatched,false);
  assert.equal(workerBoundary.side_effect_classification,'SIDE_EFFECT_NOT_APPLIED');
  assert.equal(workerBoundary.security_boundary_conclusion,'DO_NOT_GRANT_RUNNER_ACCESS_TO_HUMAN_BREAKGLASS_SSH_KEY');
  assert.equal(workerBoundary.next_gate,'WORKER_CHANNEL_ADMIN_READONLY_PRESTATE_REQUIRED');
  assert.equal(workerBoundary.verification_state,'VERIFIED');
  assert.equal(workerBoundary.readback_status,'CONFIRMED');
});

test('Z4 remains isolated from business paid VM firewall runner provider and global execution-policy effects',()=>{
  assert.equal(host.business_effects,0);assert.equal(host.production_effects,0);
  assert.equal(jea.business_effects,0);assert.equal(jea.production_effects,0);
  assert.equal(access.business_project_effect,false);assert.equal(access.production_effect,false);
  assert.equal(reconcile.business_project_effect,false);assert.equal(reconcile.production_effect,false);
  assert.equal(preflight.vm_mutation_observed,false);assert.equal(preflight.firewall_mutation_observed,false);
  assert.equal(fix.host_mutation,false);assert.equal(fix.vm_mutation,false);assert.equal(fix.firewall_mutation,false);
  assert.equal(executionPolicy.vm_mutation,false);assert.equal(executionPolicy.firewall_mutation,false);
  assert.equal(executionPolicy.runner_privilege_elevation,false);assert.equal(executionPolicy.global_execution_policy_mutation,false);
  assert.equal(executionPolicyPrestate.vm_mutation_observed,false);assert.equal(executionPolicyPrestate.firewall_mutation_observed,false);
  assert.equal(hypervDependency.vm_mutation,false);assert.equal(hypervDependency.firewall_mutation,false);
  assert.equal(hypervDependency.runner_privilege_elevation,false);assert.equal(hypervDependency.global_execution_policy_mutation,false);
  assert.equal(runtimeDependencies.vm_mutation,false);assert.equal(runtimeDependencies.firewall_mutation,false);
  assert.equal(runtimeDependencies.runner_privilege_elevation,false);assert.equal(runtimeDependencies.global_execution_policy_mutation,false);
  assert.equal(runtimeDependencies.business_project_effect,false);assert.equal(runtimeDependencies.production_effect,false);
  assert.equal(providerAcceptance.vm_mutation,false);assert.equal(providerAcceptance.public_firewall_mutation,false);
  assert.equal(providerAcceptance.runner_privilege_elevation,false);assert.equal(providerAcceptance.global_execution_policy_mutation,false);
  assert.equal(providerAcceptance.business_project_effect,false);assert.equal(providerAcceptance.production_effect,false);
  assert.equal(workerBoundary.guest_mutation,false);assert.equal(workerBoundary.vm_mutation,false);
  assert.equal(workerBoundary.provider_mutation,false);assert.equal(workerBoundary.business_project_effect,false);assert.equal(workerBoundary.production_effect,false);
  assert.equal(control.production_allowed,false);
  assert.equal(control.business_project_access_allowed,false);
  assert.equal(control.zero_incremental_paid_cost_required,true);
});
