import test from 'node:test';
import assert from 'node:assert/strict';
import {evaluateNonBypassTrust,requireNonBypass} from '../../scripts/csg-nonbypass.mjs';
const current={canonical_branch_protected:true,required_status_checks_enforcement:'off',required_checks:[],rulesets:[],normal_actor_can_push_raw:true,normal_actor_admin:true,candidate_can_modify_rules:true,candidate_can_forge_required_check:false,verifier_trust_root_pinned:false,recovery_channel_scoped:false};
const secure={canonical_branch_protected:true,required_status_checks_enforcement:'enforced',required_checks:['csg/trusted-verifier'],rulesets:['canonical-control-nonbypass'],normal_actor_can_push_raw:false,normal_actor_admin:false,candidate_can_modify_rules:false,candidate_can_forge_required_check:false,verifier_trust_root_pinned:true,recovery_channel_scoped:true};
test('01 current observed trust surface must fail closed',()=>{const r=evaluateNonBypassTrust(current);assert.equal(r.pass,false);assert.ok(r.findings.includes('REQUIRED_STATUS_CHECKS_NOT_ENFORCED'));assert.ok(r.findings.includes('NORMAL_ACTOR_RAW_PUSH_CAPABLE'));});
test('02 empty ruleset is a blocker',()=>assert.ok(evaluateNonBypassTrust({...secure,rulesets:[]}).findings.includes('NO_REPOSITORY_RULESET')));
test('03 admin normal actor is a blocker',()=>assert.ok(evaluateNonBypassTrust({...secure,normal_actor_admin:true}).findings.includes('NORMAL_ACTOR_ADMIN_CAPABLE')));
test('04 candidate rules mutation capability is a blocker',()=>assert.ok(evaluateNonBypassTrust({...secure,candidate_can_modify_rules:true}).findings.includes('CANDIDATE_CAN_MODIFY_RULES')));
test('05 unpinned verifier trust root is a blocker',()=>assert.ok(evaluateNonBypassTrust({...secure,verifier_trust_root_pinned:false}).findings.includes('VERIFIER_TRUST_ROOT_NOT_PINNED')));
test('06 unscoped recovery channel is a blocker',()=>assert.ok(evaluateNonBypassTrust({...secure,recovery_channel_scoped:false}).findings.includes('RECOVERY_CHANNEL_NOT_SCOPED')));
test('07 secure target snapshot passes',()=>assert.equal(requireNonBypass(secure).pass,true));
