import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {canonicalDigest,parseStrictJson,validateCsg,validateGitOID} from '../../scripts/csg-schema.mjs';

const H='a'.repeat(64), G='b'.repeat(40), D=`sha256:${H}`;
const ext=(path='governance/x.json',digest=D)=>({kind:'EXTERNAL_IMMUTABLE',provider:'github',repository_id_or_resource_id:1352411536,revision:G,path,digest});
const bun=(path='evidence/x.json',digest=D)=>({kind:'BUNDLE_OBJECT',path,digest});
const anchor=()=>({ref:`github://1352411536/governance/v47/current-mission.json@${G}`,revision:'20260916T001525+0800',declared_hash:D,canonicalization_version:'HUMAN_TEXT_V1'});
const git=()=>({algorithm:'sha1',hex:G});
function checkpoint(){const v={schema_version:'csg.checkpoint.v1',project_id:'CHATGPT_GLOBAL_SKILL_GOVERNANCE',checkpoint_seq:1,transition_id:'CSG-02-T1',previous_checkpoint_ref:null,migration_anchor:null,event:{type:'ATOMIC_STARTED',reason_code:'CSG02',subject_id:'CSG-02'},mission_anchor:anchor(),policy_anchor:anchor(),controller_contract:'CHAT_EXECUTION_POLICY_CONTRACT_V9_1_CANDIDATE',verifier_digest:D,lifecycle:'PAUSED',owner:null,run_ref:null,task_id:'CSG-02',attempt_id:'CSG-02-A1',attempt_epoch:1,atomic:null,last_accepted:null,remote_wip:null,active_job_refs:[],unresolved_effect_refs:[],blockers:[],last_verified_gate:null,next_legal_transition:{action:'VERIFY_LOCAL',unit_id:'CSG-02',requires:[],forbidden:['PRODUCTION']},stop_requested:false,barrier:'ACTIVE_UNIT',evidence_refs:[bun('evidence/csg02.json')],recorded_at:'2026-09-16T04:00:00Z',payload_digest:D};v.payload_digest=canonicalDigest(v);return v;}
function project(){return {schema_version:'csg.project.v1',project_id:'CHATGPT_GLOBAL_SKILL_GOVERNANCE',canonical_name:'全自動軟體工廠',aliases:[{display_name:'全自動軟體工廠',normalized_name:'全自動軟體工廠'}],normalization_version:'nfkc-casefold-v1',binding_id:'BIND-001',registration_state:'BOUND',directory_revision:3,binding_generation:1,control_locator:{provider:'github',repository_id:1352411536,ref:'refs/heads/v45/factory-control',current_path:'governance/csg/current.json'},runtime_type:'GITHUB_ACTIONS_BOUNDED',bootstrap_anchor:ext('governance/csg/bootstrap.json'),authorization_ref:ext('governance/v47/current-mission.json'),data_classification:'PUBLIC',previous_binding_ref:null,created_at:'2026-09-16T00:00:00Z',updated_at:'2026-09-16T04:00:00Z'};}
function pointer(){return {schema_version:'csg.pointer.v1',project_id:'CHATGPT_GLOBAL_SKILL_GOVERNANCE',binding_id:'BIND-001',binding_generation:1,checkpoint_seq:1,checkpoint_path:'governance/csg/checkpoints/1.json',checkpoint_digest:D,previous_control_oid:git(),transition_id:'CSG-02-T1',reader_compatibility:{min_schema:'csg.checkpoint.v1',max_schema:'csg.checkpoint.v1'}};}
function intent(){return {schema_version:'csg.effect-intent.v1',project_id:'CHATGPT_GLOBAL_SKILL_GOVERNANCE',operation_id:'OP-001',logical_action_key:'project/task/action/target',originating_transition_id:'CSG-02-T1',effect_kind:'GITHUB_REF_UPDATE',provider:'github',target:{repository_id:1352411536,ref:'refs/heads/synthetic'},request_digest:D,payload_ref:bun('effects/op-001-request.json'),idempotency:{mode:'APPLICATION',key_ref:ext('effects/op-001-key.json'),scope:'same-logical-action',valid_until:'2026-09-17T00:00:00Z'},precondition:{kind:'CAS',expected_revision:G,prestate_ref:ext('effects/op-001-prestate.json')},authorization_ref:ext('governance/v47/current-execution-policy.json'),mission_anchor:anchor(),policy_anchor:anchor(),created_by_owner_generation:1,attempt_id:'ATTEMPT-001',provider_profile_ref:ext('governance/csg/provider-profile.json'),dispatch_deadline:'2026-09-16T05:00:00Z',created_at:'2026-09-16T04:00:00Z'};}
function receipt(){return {schema_version:'csg.effect-receipt.v1',receipt_id:'RCP-001',operation_id:'OP-001',project_id:'CHATGPT_GLOBAL_SKILL_GOVERNANCE',request_digest:D,provider_target:{repository_id:1352411536,ref:'refs/heads/synthetic'},outcome:'NOT_APPLIED',attribution:{method:'SAME_SOURCE_READBACK',provider_operation_id:null,comparison:'exact ref unchanged'},observed_provider_revision:G,observed_at:'2026-09-16T04:10:00Z',readback_ref:bun('effects/op-001-readback.json'),readback_digest:D,negative_proof:{finality:true,absence_basis:'exact provider ref unchanged after request deadline',late_request_excluded:true,retention_valid:true},writer_fence_proof:ext('effects/op-001-fence.json'),reconciler_identity:'RECOVERY-001',owner_generation:2,residual_risk:'none observed',next_allowed:'SAME_ID_RETRY'};}
function evidence(){const v={schema_version:'csg.evidence.v1',evidence_id:'E-001',project_id:'CHATGPT_GLOBAL_SKILL_GOVERNANCE',subject:{unit_id:'CSG-02',source_commit:git(),contract_digest:D},category:'TEST',expected_set_ref:ext('tests/csg/expected-set.v1.json',D),verifier_ref:ext('tests/csg/schema.test.mjs',D),result:'PASS',observed_by:'VERIFIER-001',observed_at:'2026-09-16T04:20:00Z',source_refs:[{immutable_ref:ext('tests/csg/output.tap',D),digest:D,size:123,media_type:'text/plain'}],retention_until:null,archive_ref:null,data_classification:'PUBLIC',source_ancestry:['CSG-SPEC'],supersedes_ref:null,payload_digest:D};v.payload_digest=canonicalDigest(v);return v;}
function worklog(){return {schema_version:'csg.worklog.v1',source_checkpoint_seq:1,source_checkpoint_digest:D,projector_version:'csg-projector-v1',template_digest:D,current_summary:'CSG-02 candidate verified locally.',entries:[{seq:1,unit_id:'CSG-02',event:'ATOMIC_STARTED',result:'LOCAL',evidence_refs:[bun('evidence/csg02.json')]}],rendered_digest:D,stale:false};}
const bad=(fn,code)=>assert.throws(fn,e=>String(e.code||e.message).startsWith(code));
test('01 strict parser rejects duplicate JSON keys',()=>bad(()=>parseStrictJson('{"a":1,"a":2}'),'DUPLICATE_JSON_KEY'));
test('02 strict parser rejects NaN token',()=>bad(()=>parseStrictJson('{"a":NaN}'),'INVALID_JSON_TOKEN'));
test('03 unknown schema is rejected',()=>bad(()=>validateCsg({schema_version:'csg.future.v9'}),'UNKNOWN_SCHEMA'));
test('04 valid ProjectRecord passes',()=>assert.equal(validateCsg(project()).registration_state,'BOUND'));
test('05 ProjectRecord rejects unknown key',()=>{const v=project();v.current_phase='BAD';bad(()=>validateCsg(v),'ILLEGAL_OR_MISSING_KEY');});
test('06 ProjectRecord rejects illegal null',()=>{const v=project();v.canonical_name=null;bad(()=>validateCsg(v),'ILLEGAL_NULL');});
test('07 valid CanonicalControl passes',()=>assert.equal(validateCsg(pointer()).checkpoint_seq,1));
test('08 GitOID and SHA256 are not interchangeable',()=>{const v=pointer();v.previous_control_oid={algorithm:'sha1',hex:H};bad(()=>validateCsg(v),'GIT_OID_LENGTH_MISMATCH');});
test('09 valid Checkpoint with computed payload digest passes',()=>assert.equal(validateCsg(checkpoint(),{expectedMissionCanonicalizationVersion:'HUMAN_TEXT_V1'}).barrier,'ACTIVE_UNIT'));
test('10 Checkpoint rejects wrong payload digest',()=>{const v=checkpoint();v.payload_digest=D;bad(()=>validateCsg(v),'PAYLOAD_DIGEST_MISMATCH');});
test('11 Mission canonicalization version drift is rejected',()=>{const v=checkpoint();v.mission_anchor.canonicalization_version='JCS-v1';v.payload_digest=canonicalDigest(v);bad(()=>validateCsg(v,{expectedMissionCanonicalizationVersion:'HUMAN_TEXT_V1'}),'MISSION_CANONICALIZATION_VERSION_MISMATCH');});
test('12 self BundleObjectRef is rejected',()=>{const v=checkpoint();v.evidence_refs=[bun('governance/csg/checkpoints/1.json')];v.payload_digest=canonicalDigest(v);bad(()=>validateCsg(v,{selfPath:'governance/csg/checkpoints/1.json'}),'SELF_BUNDLE_REFERENCE');});
test('13 relative path escape is rejected',()=>{const v=pointer();v.checkpoint_path='../escape.json';bad(()=>validateCsg(v),'INVALID_RELATIVE_PATH');});
test('14 valid EffectIntent passes and stable operation id is data',()=>assert.equal(validateCsg(intent()).operation_id,'OP-001'));
test('15 idempotent EffectIntent requires persisted key ref',()=>{const v=intent();v.idempotency.key_ref=null;bad(()=>validateCsg(v),'IDEMPOTENCY_KEY_REQUIRED');});
test('16 NOT_APPLIED EffectReceipt requires strong negative proof',()=>{const v=receipt();v.negative_proof.retention_valid=false;bad(()=>validateCsg(v),'INSUFFICIENT_NEGATIVE_PROOF');});
test('17 EvidenceRecord rejects candidate-changed expected set',()=>{const v=evidence();bad(()=>validateCsg(v,{expectedSetDigest:`sha256:${'c'.repeat(64)}`,verifierDigest:D}),'EXPECTED_SET_MISMATCH');});
test('18 EvidenceRecord rejects candidate-changed verifier',()=>{const v=evidence();bad(()=>validateCsg(v,{expectedSetDigest:D,verifierDigest:`sha256:${'d'.repeat(64)}`}),'VERIFIER_MISMATCH');});
test('19 valid EvidenceRecord passes with pinned verifier inputs',()=>{const v=evidence();assert.equal(validateCsg(v,{expectedSetDigest:D,verifierDigest:D}).result,'PASS');});
test('20 WorklogProjection validates but remains projection-only data',()=>assert.equal(validateCsg(worklog()).stale,false));
test('21 RFC8785 implementation preserves Unicode code points without NFKC',()=>{const a=canonicalDigest({x:'é'}),b=canonicalDigest({x:'e\u0301'});assert.notEqual(a,b);});
test('22 RFC8785 implementation canonicalizes object key order deterministically',()=>assert.equal(canonicalDigest({b:1,a:2}),canonicalDigest({a:2,b:1})));
test('23 cross-runtime SHA256 agrees on canonical UTF-8 bytes when python is available',()=>{const canonical='{"a":2,"b":1}';const node=createHash('sha256').update(Buffer.from(canonical,'utf8')).digest('hex');const py=spawnSync('python3',['-c','import hashlib,sys;print(hashlib.sha256(sys.stdin.buffer.read()).hexdigest())'],{input:canonical,encoding:'utf8'});if(py.status===0)assert.equal(py.stdout.trim(),node);else assert.ok(true);});
test('24 safe integer overflow is rejected',()=>{const v=pointer();v.checkpoint_seq=9007199254740992;bad(()=>validateCsg(v),'INVALID_SAFE_INTEGER');});
