import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {readFileSync} from 'node:fs';
const read=p=>readFileSync(new URL('../../'+p,import.meta.url));
const json=p=>JSON.parse(read(p).toString('utf8'));
const canonical=v=>Array.isArray(v)?'['+v.map(canonical).join(',')+']':v&&typeof v==='object'?'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}':JSON.stringify(v);
const sha256=b=>'sha256:'+createHash('sha256').update(b).digest('hex');
const mission=json('governance/csg/v51/current-mission.json');
const policy=json('governance/csg/v51/current-execution-policy.json');
const run=json('governance/csg/v51/runs/V51-R1-001/run.json');
const contract=json('governance/csg/v51/runs/V51-R1-001/contract-r1-03.json');
test('exact Human spec is pinned under the CSG authority tree',()=>{const p='governance/csg/v51/specs/VNEXT5.1-R1-HUMAN-CURRENT-SPEC-20260929.md';const b=read(p);const oid=createHash('sha1').update(Buffer.concat([Buffer.from('blob '+b.length+'\0'),b])).digest('hex');assert.equal(b.length,5779);assert.equal(sha256(b),'sha256:29e8a4b8685afbbc8531e1a62dee0b5b072f6a28270f11bfbea9d9b6a5378bea');assert.equal(oid,'6df4a189c84ff1e53ce4ba0a90ba39eb6334e59a');assert.equal(mission.payload.current_construction_spec.canonical_path,p);assert.equal(policy.payload.current_construction_spec.blob_oid,oid);});
test('Mission and Policy hashes and revisions agree',()=>{assert.equal(mission.mission_hash,sha256(Buffer.from(canonical(mission.payload),'utf8')));assert.equal(policy.policy_hash,sha256(Buffer.from(canonical(policy.payload),'utf8')));assert.equal(policy.mission_hash,mission.mission_hash);assert.equal(policy.mission_revision_id,mission.mission_revision_id);});
test('single run task and attempt are coherent across artifacts',()=>{assert.equal(mission.payload.active_run_id,run.run_id);assert.equal(mission.payload.active_task_id,run.active_task_id);assert.equal(mission.payload.active_attempt_id,run.attempt_id);assert.equal(policy.payload.active_unit,run.active_task_id);assert.equal(run.contract_ref,'governance/csg/v51/runs/V51-R1-001/contract-r1-03.json');assert.equal(contract.contract_id,'V51-R1-CONTRACT-001-R1-03');assert.equal(contract.task_id,run.active_task_id);assert.equal(contract.run_id,run.run_id);assert.equal(run.unresolved_operation_ids.length,0);assert.equal(run.remaining_attempts,1);});
test('Human gates and four-tool boundary remain closed',()=>{assert.equal(mission.payload.authorization.production_allowed,false);assert.equal(mission.payload.authorization.paid_fallback_allowed,false);assert.equal(mission.payload.authorization.business_project_auto_admission,false);assert.equal(policy.payload.factory_mcp.public_tool_count,4);assert.equal(policy.payload.factory_mcp.trusted_caller.shared_network_service_sid_alone_sufficient,false);});
