Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$root='C:\ProgramData\PTYSD\MCP\FactoryMCP'
$rr=Join-Path $root 'state\exec-receipts'
function ReadReceipt([string]$id){$p=Join-Path $rr ($id+'.json');if(!(Test-Path -LiteralPath $p)){return [ordered]@{request_id=$id;present=$false}};try{$j=Get-Content -LiteralPath $p -Raw|ConvertFrom-Json -ErrorAction Stop;[ordered]@{request_id=$id;present=$true;schema=$j.schema;state=$j.state;project_id=$j.project_id;operation_id=$j.operation_id;run_id=$j.run_id;task_id=$j.task_id;attempt_id=$j.attempt_id;attempt_epoch=$j.attempt_epoch;timed_out=$j.timed_out;exit_code=$j.exit_code;side_effect_state=$j.side_effect_state;script_sha256=$j.script_sha256;started_at_utc=$j.started_at_utc;finished_at_utc=$j.finished_at_utc}}catch{[ordered]@{request_id=$id;present=$true;parse_ok=$false}}}
function ListMatches([string]$p){if(!(Test-Path -LiteralPath $p -PathType Container)){return @()};@(Get-ChildItem -LiteralPath $p -Force -ErrorAction SilentlyContinue|Where-Object{$_.Name -match '(?i)(p5|mtls|factory-mcp-http|trusted-callers|client|server|ca)'}|Select-Object -First 40|ForEach-Object{[ordered]@{name=$_.Name;dir=[bool]$_.PSIsContainer;last_write_utc=$_.LastWriteTimeUtc.ToString('o')}})}
function JsonMeta([string]$p){if(!(Test-Path -LiteralPath $p -PathType Leaf)){return $null};try{$j=Get-Content -LiteralPath $p -Raw|ConvertFrom-Json -ErrorAction Stop;[ordered]@{name=[IO.Path]::GetFileName($p);schema=$j.schema;project_id=$j.project_id;status=$j.status;listen_host=$j.listen_host;listen_port=$j.listen_port;trusted_identity_generation=$j.trusted_identity_generation;pid=$j.pid;observed_at=$j.observed_at;last_write_utc=(Get-Item -LiteralPath $p).LastWriteTimeUtc.ToString('o')}}catch{[ordered]@{name=[IO.Path]::GetFileName($p);parse_ok=$false}}}
$meta=@();foreach($p in @('C:\ProgramData\PTYSD\MCP\config\factory-mcp-http.json','C:\ProgramData\PTYSD\MCP\FactoryMCP\config\factory-mcp-http.json','C:\ProgramData\PTYSD\MCP\state\factory-mcp-http-health.json','C:\ProgramData\PTYSD\MCP\FactoryMCP\state\factory-mcp-http-health.json','C:\ProgramData\PTYSD\MCP\FactoryMCP\state\http-health.json')){$m=JsonMeta $p;if($null-ne$m){$meta+=$m}}
$np=@();try{foreach($p in @(Get-CimInstance Win32_Process -Filter "Name='node.exe'" -ErrorAction SilentlyContinue)){if(([string]$p.CommandLine)-match '(?i)(http-main\.mjs|factory-mcp|p5.*mtls)'){$np+=[ordered]@{pid=[int]$p.ProcessId;http_main=[bool](([string]$p.CommandLine)-match '(?i)http-main\.mjs');created=if($p.CreationDate){([DateTime]$p.CreationDate).ToUniversalTime().ToString('o')}else{$null}}}}}catch{}
$pids=@($np|ForEach-Object{$_.pid});$ls=@();if($pids.Count){try{$ls=@(Get-NetTCPConnection -State Listen -ErrorAction SilentlyContinue|Where-Object{$_.LocalAddress -in @('127.0.0.1','::1') -and $pids -contains [int]$_.OwningProcess}|Select-Object -First 20|ForEach-Object{[ordered]@{address=$_.LocalAddress;port=[int]$_.LocalPort;pid=[int]$_.OwningProcess}})}catch{}}
[ordered]@{schema='v49.p5.windows-mtls-timeout-bounded-readback.v1';readback_only=$true;original_receipt=ReadReceipt '280c25cc2543451b9ef1487667b5d443';prior_readback_receipt=ReadReceipt 'cdd28f93f92e4a63b17ef5df0d212ef9';mcp_root=ListMatches 'C:\ProgramData\PTYSD\MCP';factory_root=ListMatches $root;factory_state=ListMatches (Join-Path $root 'state');windows_temp=ListMatches 'C:\Windows\Temp';fixed_json_metadata=$meta;matching_node_processes=$np;loopback_listeners=$ls;no_recursive_scan=$true;no_private_key_content_output=$true;no_raw_log_output=$true;no_process_kill=$true;no_file_delete=$true;observed_at_utc=[DateTime]::UtcNow.ToString('o')}|ConvertTo-Json -Depth 7 -Compress
