import {createHash} from 'node:crypto';
import canonicalize from '../tools/csg/node_modules/canonicalize/lib/canonicalize.js';

const MAX_SAFE = 9007199254740991;
const ID_RE = /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/;
const DIGEST_RE = /^sha256:[0-9a-f]{64}$/;
const TIME_RE = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,9})?Z$/;
const SCHEMAS = new Set(['csg.project.v1','csg.pointer.v1','csg.checkpoint.v1','csg.effect-intent.v1','csg.effect-receipt.v1','csg.evidence.v1','csg.worklog.v1']);
function fail(code){const e=new Error(code);e.code=code;throw e;}
function object(v, code='OBJECT_REQUIRED'){if(!v||typeof v!=='object'||Array.isArray(v))fail(code);return v;}
function exactKeys(v, keys){object(v);const got=Object.keys(v).sort();const want=[...keys].sort();if(got.length!==want.length||got.some((k,i)=>k!==want[i]))fail('ILLEGAL_OR_MISSING_KEY');}
function id(v){if(typeof v!=='string'||!ID_RE.test(v))fail('INVALID_ID');return v;}
function digest(v){if(typeof v!=='string'||!DIGEST_RE.test(v))fail('INVALID_DIGEST');return v;}
function time(v){if(typeof v!=='string'||!TIME_RE.test(v))fail('INVALID_RFC3339_UTC');return v;}
function integer(v,min=1){if(!Number.isSafeInteger(v)||v<min||v>MAX_SAFE)fail('INVALID_SAFE_INTEGER');return v;}
function noNull(v,name){if(v===null)fail(`ILLEGAL_NULL:${name}`);return v;}
function relpath(v){if(typeof v!=='string'||Buffer.byteLength(v,'utf8')>512||!v||v.startsWith('/')||v.includes('\\')||v.split('/').some(p=>!p||p==='.'||p==='..'))fail('INVALID_RELATIVE_PATH');return v;}
function enumv(v,vals,code='INVALID_ENUM'){if(!vals.includes(v))fail(code);return v;}
export function validateGitOID(v){exactKeys(v,['algorithm','hex']);enumv(v.algorithm,['sha1','sha256'],'INVALID_GIT_ALGORITHM');if(typeof v.hex!=='string'||!/^[0-9a-f]+$/.test(v.hex))fail('INVALID_GIT_OID');if(v.algorithm==='sha1'&&v.hex.length!==40)fail('GIT_OID_LENGTH_MISMATCH');if(v.algorithm==='sha256'&&v.hex.length!==64)fail('GIT_OID_LENGTH_MISMATCH');return v;}
function extRef(v){exactKeys(v,['kind','provider','repository_id_or_resource_id','revision','path','digest']);if(v.kind!=='EXTERNAL_IMMUTABLE')fail('INVALID_EXTERNAL_REF_KIND');if(!String(v.provider).length||!String(v.revision).length)fail('INVALID_EXTERNAL_REF');relpath(v.path);digest(v.digest);return v;}
function bundleRef(v){exactKeys(v,['kind','path','digest']);if(v.kind!=='BUNDLE_OBJECT')fail('INVALID_BUNDLE_REF_KIND');relpath(v.path);digest(v.digest);return v;}
function artifactRef(v){object(v);if(v.kind==='EXTERNAL_IMMUTABLE')return extRef(v);if(v.kind==='BUNDLE_OBJECT')return bundleRef(v);fail('INVALID_ARTIFACT_REF');}
function anchor(v){exactKeys(v,['ref','revision','declared_hash','canonicalization_version']);if(typeof v.ref!=='string'||v.ref.length<1||v.ref.length>2048)fail('INVALID_AUTHORITY_REF');if(typeof v.revision!=='string'||!v.revision)fail('INVALID_AUTHORITY_REVISION');digest(v.declared_hash);if(typeof v.canonicalization_version!=='string'||!v.canonicalization_version)fail('INVALID_CANONICALIZATION_VERSION');return v;}
function scanJson(text){if(typeof text!=='string')fail('JSON_TEXT_REQUIRED');let i=0;const ws=()=>{while(/\s/.test(text[i]??''))i++;};function str(){if(text[i]!=='"')fail('JSON_STRING_REQUIRED');const start=i++;while(i<text.length){if(text[i]==='\\'){i+=2;continue;}if(text[i]==='"'){i++;return JSON.parse(text.slice(start,i));}i++;}fail('UNTERMINATED_JSON_STRING');}function value(depth=0){if(depth>128)fail('JSON_TOO_DEEP');ws();const c=text[i];if(c==='{')return obj(depth+1);if(c==='[')return arr(depth+1);if(c==='"')return void str();const start=i;while(i<text.length&&!/[\s,\]}]/.test(text[i]))i++;const token=text.slice(start,i);if(!token||!/^(?:true|false|null|-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?)$/.test(token))fail('INVALID_JSON_TOKEN');if(!['true','false','null'].includes(token)){const n=Number(token);if(!Number.isFinite(n))fail('NONFINITE_NUMBER');if(Number.isInteger(n)&&!Number.isSafeInteger(n))fail('UNSAFE_INTEGER');}}function obj(depth){i++;ws();const keys=new Set();if(text[i]==='}'){i++;return;}while(true){ws();const k=str();if(keys.has(k))fail(`DUPLICATE_JSON_KEY:${k}`);keys.add(k);ws();if(text[i++]!==':')fail('JSON_COLON_REQUIRED');value(depth);ws();if(text[i]==='}'){i++;return;}if(text[i++]!==',')fail('JSON_COMMA_REQUIRED');}}function arr(depth){i++;ws();if(text[i]===']'){i++;return;}while(true){value(depth);ws();if(text[i]===']'){i++;return;}if(text[i++]!==',')fail('JSON_COMMA_REQUIRED');}}value(0);ws();if(i!==text.length)fail('JSON_TRAILING_DATA');}
export function parseStrictJson(text){scanJson(text);return JSON.parse(text);}
export function canonicalDigest(value){const copy=structuredClone(value);if(copy&&typeof copy==='object'&&!Array.isArray(copy))delete copy.payload_digest;const bytes=Buffer.from(canonicalize(copy),'utf8');return `sha256:${createHash('sha256').update(bytes).digest('hex')}`;}
export function assertPayloadDigest(v){digest(v.payload_digest);const got=canonicalDigest(v);if(got!==v.payload_digest)fail('PAYLOAD_DIGEST_MISMATCH');return v;}
function rejectSelfRef(v,selfPath){if(!selfPath)return;const seen=new Set();function walk(x){if(!x||typeof x!=='object'||seen.has(x))return;seen.add(x);if(x.kind==='BUNDLE_OBJECT'&&x.path===selfPath)fail('SELF_BUNDLE_REFERENCE');for(const y of Array.isArray(x)?x:Object.values(x))walk(y);}walk(v);}
const KEYS={'csg.project.v1':['schema_version','project_id','canonical_name','aliases','normalization_version','binding_id','registration_state','directory_revision','binding_generation','control_locator','runtime_type','bootstrap_anchor','authorization_ref','data_classification','previous_binding_ref','created_at','updated_at'],'csg.pointer.v1':['schema_version','project_id','binding_id','binding_generation','checkpoint_seq','checkpoint_path','checkpoint_digest','previous_control_oid','transition_id','reader_compatibility'],'csg.checkpoint.v1':['schema_version','project_id','checkpoint_seq','transition_id','previous_checkpoint_ref','migration_anchor','event','mission_anchor','policy_anchor','controller_contract','verifier_digest','lifecycle','owner','run_ref','task_id','attempt_id','attempt_epoch','atomic','last_accepted','remote_wip','active_job_refs','unresolved_effect_refs','blockers','last_verified_gate','next_legal_transition','stop_requested','barrier','evidence_refs','recorded_at','payload_digest'],'csg.effect-intent.v1':['schema_version','project_id','operation_id','logical_action_key','originating_transition_id','effect_kind','provider','target','request_digest','payload_ref','idempotency','precondition','authorization_ref','mission_anchor','policy_anchor','created_by_owner_generation','attempt_id','provider_profile_ref','dispatch_deadline','created_at'],'csg.effect-receipt.v1':['schema_version','receipt_id','operation_id','project_id','request_digest','provider_target','outcome','attribution','observed_provider_revision','observed_at','readback_ref','readback_digest','negative_proof','writer_fence_proof','reconciler_identity','owner_generation','residual_risk','next_allowed'],'csg.evidence.v1':['schema_version','evidence_id','project_id','subject','category','expected_set_ref','verifier_ref','result','observed_by','observed_at','source_refs','retention_until','archive_ref','data_classification','source_ancestry','supersedes_ref','payload_digest'],'csg.worklog.v1':['schema_version','source_checkpoint_seq','source_checkpoint_digest','projector_version','template_digest','current_summary','entries','rendered_digest','stale']};
export function validateCsg(v,ctx={}){object(v);if(!SCHEMAS.has(v.schema_version))fail('UNKNOWN_SCHEMA');exactKeys(v,KEYS[v.schema_version]);rejectSelfRef(v,ctx.selfPath);switch(v.schema_version){case 'csg.project.v1':return validateProject(v);case 'csg.pointer.v1':return validatePointer(v);case 'csg.checkpoint.v1':return validateCheckpoint(v,ctx);case 'csg.effect-intent.v1':return validateIntent(v);case 'csg.effect-receipt.v1':return validateReceipt(v);case 'csg.evidence.v1':return validateEvidence(v,ctx);case 'csg.worklog.v1':return validateWorklog(v);}}
function validateProject(v){id(v.project_id);noNull(v.canonical_name,'canonical_name');if(typeof v.canonical_name!=='string'||[...v.canonical_name].length<1||[...v.canonical_name].length>256)fail('INVALID_CANONICAL_NAME');if(!Array.isArray(v.aliases)||v.aliases.length>32)fail('INVALID_ALIASES');for(const a of v.aliases){exactKeys(a,['display_name','normalized_name']);if(!a.display_name||!a.normalized_name)fail('INVALID_ALIAS');}id(v.binding_id);enumv(v.registration_state,['RESERVED','BOUND','RETIRED']);integer(v.directory_revision);integer(v.binding_generation);if(v.registration_state==='BOUND'&&v.control_locator===null)fail('BOUND_REQUIRES_LOCATOR');if(v.control_locator!==null){exactKeys(v.control_locator,['provider','repository_id','ref','current_path']);if(v.control_locator.provider!=='github'||!Number.isSafeInteger(v.control_locator.repository_id)||v.control_locator.repository_id<1)fail('INVALID_LOCATOR');relpath(v.control_locator.current_path);}if(v.runtime_type!=='GITHUB_ACTIONS_BOUNDED')fail('INVALID_RUNTIME_TYPE');if(v.bootstrap_anchor!==null)extRef(v.bootstrap_anchor);if(v.registration_state==='BOUND'&&v.bootstrap_anchor===null)fail('BOUND_REQUIRES_BOOTSTRAP_ANCHOR');extRef(v.authorization_ref);enumv(v.data_classification,['PUBLIC','INTERNAL','CONFIDENTIAL']);if(v.previous_binding_ref!==null)extRef(v.previous_binding_ref);time(v.created_at);time(v.updated_at);return v;}
function validatePointer(v){id(v.project_id);id(v.binding_id);integer(v.binding_generation);integer(v.checkpoint_seq);relpath(v.checkpoint_path);digest(v.checkpoint_digest);validateGitOID(v.previous_control_oid);id(v.transition_id);exactKeys(v.reader_compatibility,['min_schema','max_schema']);if(v.reader_compatibility.min_schema!=='csg.checkpoint.v1'||v.reader_compatibility.max_schema!=='csg.checkpoint.v1')fail('UNSUPPORTED_READER_RANGE');return v;}
function validateCheckpoint(v,ctx){id(v.project_id);integer(v.checkpoint_seq);id(v.transition_id);if(v.previous_checkpoint_ref!==null)extRef(v.previous_checkpoint_ref);exactKeys(v.event,['type','reason_code','subject_id']);enumv(v.event.type,['ATOMIC_STARTED','ATOMIC_ACCEPTED','GATE_PASS','BLOCKED','WAITING_HUMAN','STOP','MISSION_REBASE','POLICY_REBASE','EFFECT_INTENT','DISPATCH_ARMED','EFFECT_RECONCILED','TERMINAL','DR_COMPLETED','MIGRATION_CUTOVER']);id(v.event.reason_code);id(v.event.subject_id);anchor(v.mission_anchor);anchor(v.policy_anchor);if(ctx.expectedMissionCanonicalizationVersion&&v.mission_anchor.canonicalization_version!==ctx.expectedMissionCanonicalizationVersion)fail('MISSION_CANONICALIZATION_VERSION_MISMATCH');digest(v.verifier_digest);enumv(v.lifecycle,['ACTIVE','PAUSED','TERMINAL','ARCHIVED']);if(v.owner!==null){exactKeys(v.owner,['principal_id','owner_generation','scope','lease_until']);id(v.owner.principal_id);integer(v.owner.owner_generation);time(v.owner.lease_until);}if(v.run_ref!==null)extRef(v.run_ref);if(v.attempt_epoch!==null)integer(v.attempt_epoch);if(!Array.isArray(v.active_job_refs)||v.active_job_refs.length>1)fail('ACTIVE_JOB_BOUND');if(!Array.isArray(v.unresolved_effect_refs)||v.unresolved_effect_refs.length>1)fail('UNRESOLVED_EFFECT_BOUND');for(const r of v.unresolved_effect_refs)artifactRef(r);if(!Array.isArray(v.evidence_refs)||v.evidence_refs.length>64)fail('EVIDENCE_BOUND');for(const r of v.evidence_refs)artifactRef(r);enumv(v.barrier,['CLEAN','ACTIVE_UNIT','RECONCILE_REQUIRED','WAITING_HUMAN']);time(v.recorded_at);assertPayloadDigest(v);return v;}
function validateIntent(v){id(v.project_id);id(v.operation_id);if(typeof v.logical_action_key!=='string'||!v.logical_action_key)fail('INVALID_LOGICAL_ACTION_KEY');id(v.originating_transition_id);digest(v.request_digest);artifactRef(v.payload_ref);exactKeys(v.idempotency,['mode','key_ref','scope','valid_until']);enumv(v.idempotency.mode,['PROVIDER','APPLICATION','NONE']);if(v.idempotency.mode!=='NONE'&&v.idempotency.key_ref===null)fail('IDEMPOTENCY_KEY_REQUIRED');if(v.idempotency.key_ref!==null)extRef(v.idempotency.key_ref);time(v.idempotency.valid_until);exactKeys(v.precondition,['kind','expected_revision','prestate_ref']);enumv(v.precondition.kind,['CAS','ETAG','REVISION','NONE']);if(v.precondition.kind!=='NONE'&&v.precondition.expected_revision===null)fail('PRECONDITION_REVISION_REQUIRED');if(v.precondition.prestate_ref!==null)extRef(v.precondition.prestate_ref);extRef(v.authorization_ref);anchor(v.mission_anchor);anchor(v.policy_anchor);integer(v.created_by_owner_generation);id(v.attempt_id);extRef(v.provider_profile_ref);time(v.dispatch_deadline);time(v.created_at);return v;}
function validateReceipt(v){id(v.receipt_id);id(v.operation_id);id(v.project_id);digest(v.request_digest);enumv(v.outcome,['CONFIRMED','NOT_APPLIED','PARTIAL_OR_AMBIGUOUS']);exactKeys(v.attribution,['method','provider_operation_id','comparison']);time(v.observed_at);artifactRef(v.readback_ref);digest(v.readback_digest);if(v.outcome==='NOT_APPLIED'){if(v.negative_proof===null)fail('NOT_APPLIED_REQUIRES_NEGATIVE_PROOF');exactKeys(v.negative_proof,['finality','absence_basis','late_request_excluded','retention_valid']);if(v.negative_proof.finality!==true||v.negative_proof.late_request_excluded!==true||v.negative_proof.retention_valid!==true)fail('INSUFFICIENT_NEGATIVE_PROOF');}if(v.writer_fence_proof!==null)extRef(v.writer_fence_proof);id(v.reconciler_identity);integer(v.owner_generation);enumv(v.next_allowed,['CONTINUE','SAME_ID_RETRY','WAIT','HUMAN_GATE']);return v;}
function validateEvidence(v,ctx){id(v.evidence_id);id(v.project_id);exactKeys(v.subject,['unit_id','source_commit','contract_digest']);id(v.subject.unit_id);validateGitOID(v.subject.source_commit);digest(v.subject.contract_digest);enumv(v.category,['TEST','PROVIDER_READBACK','AUTHORIZATION','INCIDENT','DR','MIGRATION']);extRef(v.expected_set_ref);extRef(v.verifier_ref);if(ctx.expectedSetDigest&&v.expected_set_ref.digest!==ctx.expectedSetDigest)fail('EXPECTED_SET_MISMATCH');if(ctx.verifierDigest&&v.verifier_ref.digest!==ctx.verifierDigest)fail('VERIFIER_MISMATCH');enumv(v.result,['PASS','FAIL','PARTIAL','UNVERIFIED']);id(v.observed_by);time(v.observed_at);if(!Array.isArray(v.source_refs)||v.source_refs.length<1||v.source_refs.length>64)fail('INVALID_SOURCE_REFS');for(const s of v.source_refs){exactKeys(s,['immutable_ref','digest','size','media_type']);extRef(s.immutable_ref);digest(s.digest);if(!Number.isSafeInteger(s.size)||s.size<0)fail('INVALID_SOURCE_SIZE');}if(v.retention_until!==null)time(v.retention_until);if(v.archive_ref!==null)extRef(v.archive_ref);enumv(v.data_classification,['PUBLIC','INTERNAL','CONFIDENTIAL']);if(!Array.isArray(v.source_ancestry)||v.source_ancestry.length>64)fail('INVALID_SOURCE_ANCESTRY');if(v.supersedes_ref!==null)extRef(v.supersedes_ref);assertPayloadDigest(v);return v;}
function validateWorklog(v){integer(v.source_checkpoint_seq);digest(v.source_checkpoint_digest);if(typeof v.projector_version!=='string'||!v.projector_version)fail('INVALID_PROJECTOR_VERSION');digest(v.template_digest);if(typeof v.current_summary!=='string'||Buffer.byteLength(v.current_summary,'utf8')>4096)fail('INVALID_SUMMARY');if(!Array.isArray(v.entries)||v.entries.length>256)fail('INVALID_WORKLOG_ENTRIES');digest(v.rendered_digest);if(typeof v.stale!=='boolean')fail('INVALID_STALE_FLAG');return v;}
