import test from 'node:test';
import assert from 'node:assert/strict';
import { createJobSupervisor } from '../mutation-supervisor.mjs';
const H=c=>`sha256:${c.repeat(64)}`; const C=c=>c.repeat(40);
const pre=()=>({base_commit:C('a'),base_tree:C('b'),file_hashes:{'src/a.txt':H('1')}});
function runner(){let terminal=false;return{set terminal(v){terminal=v},async start(){return{process_ref:'proc-1',status:'RUNNING'}},async poll(){return{status:terminal?'SUCCEEDED':'RUNNING',events:[],cursor:null}},async cancel(){}}}
const identity={attempt_id:'ATTEMPT-001',attempt_epoch:1};
async function ready(id){const r=runner();const s=createJobSupervisor({cell_id:id,runner:r,initial_prestate:pre()});await s.start({job_id:'JOB-1',launch_key:'LAUNCH-1',...identity});r.terminal=true;await s.poll('JOB-1');return{s,r};}
test('claim increments activity revision; settle only drains lease',async()=>{const{s}=await ready('d5-lease');const c=s.claim_activity('JOB-1','ACT-1',identity);assert.equal(c.activity_revision,1);assert.equal(c.active_lease_count,1);const x=s.settle_activity('JOB-1','ACT-1',c.activity_token,identity);assert.equal(x.activity_revision,1);assert.equal(x.active_lease_count,0);});
test('concurrent claim invalidates completion candidate until re-begin',async()=>{const{s}=await ready('d5-stale-candidate');const b=s.begin_completion('JOB-1',identity);const c=s.claim_activity('JOB-1','ACT-1',identity);s.settle_activity('JOB-1','ACT-1',c.activity_token,identity);assert.throws(()=>s.commit_completion('JOB-1',{...identity,completion_id:'COMP-1',completion_candidate_revision:b.completion_candidate_revision,unresolved_effect_count:0,verifier_pass:true}),/COMPLETION_CANDIDATE_STALE/);const b2=s.begin_completion('JOB-1',identity);const done=s.commit_completion('JOB-1',{...identity,completion_id:'COMP-1',completion_candidate_revision:b2.completion_candidate_revision,unresolved_effect_count:0,verifier_pass:true});assert.equal(done.state,'COMPLETED');});
test('active lease blocks completion commit',async()=>{const{s}=await ready('d5-active');const c=s.claim_activity('JOB-1','ACT-1',identity);const b=s.begin_completion('JOB-1',identity);assert.throws(()=>s.commit_completion('JOB-1',{...identity,completion_id:'COMP-1',completion_candidate_revision:b.completion_candidate_revision,unresolved_effect_count:0,verifier_pass:true}),/ACTIVE_LEASES_BLOCK_COMPLETION/);s.settle_activity('JOB-1','ACT-1',c.activity_token,identity);const done=s.commit_completion('JOB-1',{...identity,completion_id:'COMP-1',completion_candidate_revision:b.completion_candidate_revision,unresolved_effect_count:0,verifier_pass:true});assert.equal(done.state,'COMPLETED');});
test('unresolved effect or missing verifier blocks completion',async()=>{const{s}=await ready('d5-proof');const b=s.begin_completion('JOB-1',identity);assert.throws(()=>s.commit_completion('JOB-1',{...identity,completion_id:'COMP-1',completion_candidate_revision:b.completion_candidate_revision,unresolved_effect_count:1,verifier_pass:true}),/UNRESOLVED_EFFECTS_BLOCK_COMPLETION/);assert.throws(()=>s.commit_completion('JOB-1',{...identity,completion_id:'COMP-1',completion_candidate_revision:b.completion_candidate_revision,unresolved_effect_count:0,verifier_pass:false}),/VERIFIER_PASS_REQUIRED/);});
test('ACK-loss duplicate commit is idempotent for exact completion id',async()=>{const{s}=await ready('d5-ack');const b=s.begin_completion('JOB-1',identity);const p={...identity,completion_id:'COMP-1',completion_candidate_revision:b.completion_candidate_revision,unresolved_effect_count:0,verifier_pass:true};const a=s.commit_completion('JOB-1',p),b2=s.commit_completion('JOB-1',p);assert.equal(a.completion_digest,b2.completion_digest);assert.equal(b2.reused,true);assert.throws(()=>s.commit_completion('JOB-1',{...p,completion_id:'COMP-2'}),/COMPLETION_ALREADY_COMMITTED/);});
test('late activity after completion is terminal reject',async()=>{const{s}=await ready('d5-late');const b=s.begin_completion('JOB-1',identity);s.commit_completion('JOB-1',{...identity,completion_id:'COMP-1',completion_candidate_revision:b.completion_candidate_revision,unresolved_effect_count:0,verifier_pass:true});assert.throws(()=>s.claim_activity('JOB-1','ACT-LATE',identity),/LATE_ACTIVITY_AFTER_COMPLETION/);assert.throws(()=>s.settle_activity('JOB-1','ACT-LATE','a_fake',identity),/LATE_ACTIVITY_AFTER_COMPLETION/);});
test('crash between begin and commit becomes RECOVERY_REQUIRED',async()=>{const{s}=await ready('d5-crash');const b=s.begin_completion('JOB-1',identity);const r=s.record_interruption('JOB-1',identity);assert.equal(r.state,'RECOVERY_REQUIRED');assert.throws(()=>s.commit_completion('JOB-1',{...identity,completion_id:'COMP-1',completion_candidate_revision:b.completion_candidate_revision,unresolved_effect_count:0,verifier_pass:true}),/RECOVERY_REQUIRED/);});
test('stale attempt or epoch cannot claim, settle, begin or commit',async()=>{const{s}=await ready('d5-stale');assert.throws(()=>s.claim_activity('JOB-1','ACT-1',{...identity,attempt_epoch:2}),/STALE_EPOCH/);assert.throws(()=>s.begin_completion('JOB-1',{...identity,attempt_id:'ATTEMPT-OLD'}),/STALE_ATTEMPT/);const b=s.begin_completion('JOB-1',identity);assert.throws(()=>s.commit_completion('JOB-1',{...identity,attempt_epoch:2,completion_id:'COMP-1',completion_candidate_revision:b.completion_candidate_revision,unresolved_effect_count:0,verifier_pass:true}),/STALE_EPOCH/);});
test('duplicate activity claim is rejected',async()=>{const{s}=await ready('d5-dup');s.claim_activity('JOB-1','ACT-1',identity);assert.throws(()=>s.claim_activity('JOB-1','ACT-1',identity),/DUPLICATE_ACTIVITY_CLAIM/);});
test('begin before runner success is rejected',async()=>{const r=runner();const s=createJobSupervisor({cell_id:'d5-not-ready',runner:r,initial_prestate:pre()});await s.start({job_id:'JOB-1',launch_key:'LAUNCH-1',...identity});assert.throws(()=>s.begin_completion('JOB-1',identity),/JOB_NOT_READY_FOR_COMPLETION/);});
