import test from 'node:test';
import assert from 'node:assert/strict';
import { createJobSupervisor, supervisorDigest } from '../mutation-supervisor.mjs';
const H = c => `sha256:${c.repeat(64)}`;
const C = c => c.repeat(40);
const pre = () => ({ base_commit:C('a'), base_tree:C('b'), file_hashes:{'src/a.txt':H('1'),'src/b.txt':H('2')} });
function runner(){ let starts=0,cancels=0,polls=0,terminal=false,quiet=false; return { get starts(){return starts},get cancels(){return cancels},set terminal(v){terminal=v},set quiet(v){quiet=v},async start(s){starts++;return {process_ref:`proc-${s.launch_key}`,status:'RUNNING'}},async poll(ref,{cursor}){polls++;return {status:terminal?'SUCCEEDED':'RUNNING',events:quiet?[]:[`poll-${polls}`,'x'.repeat(1000)],cursor:cursor??'R'.repeat(1000)}},async cancel(){cancels++}}; }
const make = (id,r=runner(),limits={max_output_bytes:96,max_cursor_bytes:48,max_events:4}) => ({r,s:createJobSupervisor({cell_id:id,runner:r,initial_prestate:pre(),limits})});
test('stale base commit/tree/file hash reject', async()=>{let {s}=make('d4-stale'); await assert.rejects(s.mutate({...pre(),base_commit:C('c')},async()=>pre()),/STALE_BASE_HASH:base_commit/); await assert.rejects(s.mutate({...pre(),base_tree:C('c')},async()=>pre()),/STALE_BASE_HASH:base_tree/); const p=pre();p.file_hashes['src/a.txt']=H('9'); await assert.rejects(s.mutate(p,async()=>pre()),/STALE_FILE_HASH:src\/a.txt/);});
test('same cell has one mutation lane across handlers', async()=>{const r=runner(),a=createJobSupervisor({cell_id:'d4-lane',runner:r,initial_prestate:pre()}),b=createJobSupervisor({cell_id:'d4-lane',runner:r,initial_prestate:pre()}); let release; const wait=new Promise(x=>release=x); const first=a.mutate(pre(),async p=>{await wait;return p}); await new Promise(x=>setImmediate(x)); await assert.rejects(b.mutate(pre(),async p=>p),/MUTATION_LANE_BUSY/); release(); await first;});
test('successful mutation advances exactly one revision and deterministic snapshot digest', async()=>{const {s}=make('d4-mutate'); const next={base_commit:C('c'),base_tree:C('d'),file_hashes:{'src/a.txt':H('3')}}; const out=await s.mutate(pre(),async()=>({...next,result:'ok'})); assert.equal(out.mutation_revision,1);assert.equal(out.result,'ok');assert.equal(supervisorDigest(s.snapshot()),supervisorDigest(s.snapshot()));});
test('foreground to background reuses one process', async()=>{const {s,r}=make('d4-reuse'); const a=await s.start({job_id:'job1',launch_key:'launch1',mode:'foreground'}); const b=await s.start({job_id:'job2',launch_key:'launch1',mode:'background'}); assert.equal(r.starts,1);assert.equal(a.process_ref,b.process_ref);assert.equal(b.mode,'background');assert.equal(b.reused,true);});
test('handler disappearance neither completes nor kills long job', async()=>{const r=runner(); let h=createJobSupervisor({cell_id:'d4-handler',runner:r,initial_prestate:pre()}); const started=await h.start({job_id:'job1',launch_key:'launch1',mode:'foreground'}); h=null; const h2=createJobSupervisor({cell_id:'d4-handler',runner:r,initial_prestate:pre()}); const p=await h2.poll(started.job_id,0,null); assert.equal(p.status,'RUNNING');assert.equal(r.cancels,0);assert.equal(r.starts,1);});
test('explicit cancel is idempotent and does not invent terminal state', async()=>{const {s,r}=make('d4-cancel');await s.start({job_id:'job1',launch_key:'launch1'});const a=await s.cancel('job1'),b=await s.cancel('job1');assert.equal(r.cancels,1);assert.equal(a.status,'RUNNING');assert.equal(b.status,'RUNNING');});
test('poll cursor is opaque and bounded; event output bounded', async()=>{const {s}=make('d4-bounds');await s.start({job_id:'job1',launch_key:'launch1'});const p=await s.poll('job1',0,null);assert.ok(Buffer.byteLength(p.cursor,'utf8')<=48);assert.ok(Buffer.byteLength(JSON.stringify(p.events),'utf8')<=96);assert.ok(p.cursor.startsWith('c_'));});
test('unknown or oversized cursor fails closed', async()=>{const {s}=make('d4-cursor');await s.start({job_id:'job1',launch_key:'launch1'});await assert.rejects(s.poll('job1',0,'c_unknown'),/UNKNOWN_CURSOR/);await assert.rejects(s.poll('job1',0,'x'.repeat(49)),/INVALID_CURSOR/);});
test('since_revision returns unchanged only when poll observes no state/output delta', async()=>{const {s,r}=make('d4-since');await s.start({job_id:'job1',launch_key:'launch1'});const a=await s.poll('job1',0,null);r.quiet=true;const b=await s.poll('job1',a.revision,a.cursor);assert.deepEqual(b.events,[]);assert.equal(b.unchanged,true);await assert.rejects(s.poll('job1',b.revision+1,b.cursor),/FUTURE_REVISION/);});
test('runner terminal state only becomes terminal through poll readback', async()=>{const {s,r}=make('d4-terminal');await s.start({job_id:'job1',launch_key:'launch1'});r.terminal=true;const p=await s.poll('job1',0,null);assert.equal(p.status,'SUCCEEDED');});
test('different cells have independent mutation lanes', async()=>{const ra=runner(),rb=runner(),a=createJobSupervisor({cell_id:'d4-cell-a',runner:ra,initial_prestate:pre()}),b=createJobSupervisor({cell_id:'d4-cell-b',runner:rb,initial_prestate:pre()});let release;const wait=new Promise(x=>release=x);const pa=a.mutate(pre(),async p=>{await wait;return p});await new Promise(x=>setImmediate(x));const pb=await b.mutate(pre(),async p=>p);assert.equal(pb.mutation_revision,1);release();await pa;});
