import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import { computeVerifierBundleDigest, createVerifierBindingReceipt, validateVerifierBindingReceipt, admitVerifierOutcome } from '../verifier-binding.mjs';
const D = c => `sha256:${c.repeat(64)}`;
const G = c => c.repeat(40);
const root = path.resolve('/tmp/candidate');
const cwd = path.join(root, 'src');
const bundle = () => computeVerifierBundleDigest({verifier_source_digest:D('1'),expected_case_digests:[D('3'),D('2')],anchor_digest:D('4')});
const receipt = () => createVerifierBindingReceipt({candidate_commit:G('a'),candidate_tree:G('b'),worktree_root:root,cwd,contract_digest:D('5'),verifier_digest:bundle()});
const observation = () => ({candidate_commit:G('a'),candidate_tree:G('b'),worktree_root:root,cwd,contract_digest:D('5'),verifier_digest:bundle(),source_checkout_verdict:'PASS',candidate_verdict:'PASS',candidate_exit_code:0,tests_total:3,tests_pass:3,tests_fail:0,tests_skipped:0});

test('receipt binds exact candidate commit tree worktree cwd contract and verifier',()=>{const r=receipt();assert.equal(validateVerifierBindingReceipt(r).binding_digest,r.binding_digest);assert.equal(r.candidate_commit,G('a'));assert.equal(r.candidate_tree,G('b'));});
test('verifier bundle digest is deterministic and expected-case order independent',()=>{const a=bundle(),b=computeVerifierBundleDigest({verifier_source_digest:D('1'),expected_case_digests:[D('2'),D('3')],anchor_digest:D('4')});assert.equal(a,b);});
test('framework/source PASS cannot rescue candidate FAIL',()=>{const o=observation();o.candidate_verdict='FAIL';o.candidate_exit_code=1;o.tests_fail=1;o.tests_pass=2;assert.throws(()=>admitVerifierOutcome(receipt(),o),/CANDIDATE_VERIFICATION_FAILED/);});
test('wrong candidate commit or tree is rejected',()=>{for(const field of ['candidate_commit','candidate_tree']){const o=observation();o[field]=G('c');assert.throws(()=>admitVerifierOutcome(receipt(),o),new RegExp(`VERIFIER_BINDING_MISMATCH_${field.toUpperCase()}`));}});
test('wrong worktree or cwd is rejected',()=>{let o=observation();o.worktree_root=path.resolve('/tmp/source');o.cwd=path.join(o.worktree_root,'src');assert.throws(()=>admitVerifierOutcome(receipt(),o),/VERIFIER_BINDING_MISMATCH_WORKTREE_ROOT/);o=observation();o.cwd=path.join(root,'other');assert.throws(()=>admitVerifierOutcome(receipt(),o),/VERIFIER_BINDING_MISMATCH_CWD/);});
test('candidate-modified verifier source is rejected by bundle binding',()=>{const o=observation();o.verifier_digest=computeVerifierBundleDigest({verifier_source_digest:D('9'),expected_case_digests:[D('2'),D('3')],anchor_digest:D('4')});assert.throws(()=>admitVerifierOutcome(receipt(),o),/VERIFIER_BINDING_MISMATCH_VERIFIER_DIGEST/);});
test('candidate-modified expected case is rejected by bundle binding',()=>{const o=observation();o.verifier_digest=computeVerifierBundleDigest({verifier_source_digest:D('1'),expected_case_digests:[D('2'),D('9')],anchor_digest:D('4')});assert.throws(()=>admitVerifierOutcome(receipt(),o),/VERIFIER_BINDING_MISMATCH_VERIFIER_DIGEST/);});
test('candidate-modified anchor is rejected by bundle binding',()=>{const o=observation();o.verifier_digest=computeVerifierBundleDigest({verifier_source_digest:D('1'),expected_case_digests:[D('2'),D('3')],anchor_digest:D('9')});assert.throws(()=>admitVerifierOutcome(receipt(),o),/VERIFIER_BINDING_MISMATCH_VERIFIER_DIGEST/);});
test('zero tests cannot pass',()=>{const o=observation();o.tests_total=0;o.tests_pass=0;assert.throws(()=>admitVerifierOutcome(receipt(),o),/ZERO_TESTS_CANNOT_PASS/);});
test('all skipped cannot pass',()=>{const o=observation();o.tests_total=3;o.tests_pass=0;o.tests_skipped=3;assert.throws(()=>admitVerifierOutcome(receipt(),o),/ALL_TESTS_SKIPPED_CANNOT_PASS/);});
test('tampered binding digest is rejected',()=>{const r=receipt();r.binding_digest=D('9');assert.throws(()=>admitVerifierOutcome(r,observation()),/VERIFIER_BINDING_DIGEST_MISMATCH/);});
test('exact candidate PASS is admitted even when source verdict is informational',()=>{const out=admitVerifierOutcome(receipt(),observation());assert.equal(out.accepted,true);assert.equal(out.tests.pass,3);assert.equal(out.source_checkout_verdict,'PASS');});
